-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"
-   id: go-imports
    name: 'go imports'
    entry: run-go-imports.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `goimports`, requires golang"
-   id: go-vet
    name: 'go vet'
    entry: run-go-vet.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go vet`, requires golang"
    args: [-over=15]
-   id: golangci-lint
    name: 'golangci-lint'
    entry: run-golangci-lint.sh
    types: [go]
    language: 'script'
    pass_filenames: false
    description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"
-   id: go-critic
    name: 'go-critic'
    entry: run-go-critic.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go-critic`, requires https://github.com/go-critic/go-critic"
-   id: go-all-tests
    name: 'go-all-tests'
    entry: run-go-all-tests.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"
-   id: go-unit-tests
    name: 'go-unit-tests'
    entry: run-go-unit-tests.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"
-   id: go-build
    name: 'go-build'
    entry: run-go-build.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go build`, requires golang"
-   id: go-mod-tidy
    name: 'go-mod-tidy'
    entry: run-go-mod-tidy.sh
    pass_filenames: false
    language: 'script'
    description: "Runs `go mod tidy -v`, requires golang"
